driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6.9
  - name: centos-7.3

suites:
  #----------------------------------------------------------- suite[fcgiwrap]
  - name: fcgiwrap
    run_list:
      - 'recipe[fcgiwrap_rpm::default]'
    attributes:
      fcgiwrap:
        pre_tidy: false
        post_tidy: false
