---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: parallels
    driver:
      provider: parallels
      box: parallels/centos-6.5
      customize:
        on_window_close: keep-running
      synced_folders:
        - - .products
          - /home/vagrant/products
          - ':create => true, :disabled => false'

suites:
  #------------------------------------------------------------------ fcgiwrap
  - name: fcgiwrap
    run_list:
      - 'recipe[fcgiwrap.rpm::default]'
    attributes:
      fcgiwrap:
        pre_tidy: false
        post_tidy: false
