---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  #------------------------------------------------------- provider[parallels]
  - name: parallels
    driver:
      provider: parallels
      box: parallels/centos-6.5
      customize:
        on_window_close: keep-running
      synced_folders:
        - - .products
          - /home/vagrant/products
          - ':create => true, :disabled => false'

  #------------------------------------------------------ provider[virtualbox]
  # - name: virtualbox
  #   driver:
  #     provider: virtualbox
  #     box: chef/centos-6.5
  #     synced_folders:
  #       - - .products
  #         - /home/vagrant/products
  #         - ':create => true, :disabled => false'

suites:
  #----------------------------------------------------------- suite[fcgiwrap]
  - name: fcgiwrap
    run_list:
      - 'recipe[fcgiwrap_rpm::default]'
    attributes:
      fcgiwrap:
        pre_tidy: false
        post_tidy: false
